{% set version = "3.2.0" %}

package:
  name: xerces-c
  version: {{ version }}

source:
  url: http://apache.uberglobalmirror.com//xerces/c/3/sources/xerces-c-{{ version }}.tar.xz
  sha1: d5cc1389a519c6d1227aec666903563bb4ac7d52

build:
  number: 2
  run_exports:
    # changes SO names at minor rev
    - {{ pin_subpackage('xerces-c', max_pin='x.x') }}

requirements:
  build:
    - perl  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
  host:
    - icu   # [not win]

test:
  commands:
    - conda inspect linkages -p $PREFIX xerces-c  # [not win]
    - conda inspect objects -p $PREFIX xerces-c  # [osx]

about:
  home: http://xerces.apache.org/xerces-c/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Xerces-C++ is a validating XML parser written in a portable subset of C++.'

extra:
  recipe-maintainers:
    - gillins
    - groutr
    - ocefpaf
