{% set version = "3.2.4" %}

package:
  name: xerces-c
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/xerces/c/3/sources/xerces-c-{{ version }}.tar.gz
  sha256: 3d8ec1c7f94e38fee0e4ca5ad1e1d9db23cbf3a10bba626f6b4afa2dedafe5ab

build:
  number: 1
  run_exports:
    # changes SO names at minor rev
    - {{ pin_subpackage('xerces-c', max_pin='x.x') }}

requirements:
  build:
    - perl  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - make   # [not win]
    - libtool # [not win]
    - clang  # [osx]
  host:
    - icu 73  # [not win]
    - cctools 949.0.1  # [osx]

about:
  home: https://xerces.apache.org/xerces-c/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Xerces-C++ is a validating XML parser written in a portable subset of C++.'
  description: |
    Xerces-C++ makes it easy to give your application the ability to read and write XML data. A shared library is provided for parsing, generating, manipulating, and validating XML documents using the DOM, SAX, and SAX2 APIs.
  dev_url: https://github.com/apache/xerces-c
  doc_url: https://xerces.apache.org/xerces-c/program-3.html

extra:
  recipe-maintainers:
    - gillins
    - groutr
    - ocefpaf
