{% set version = "3.1.4" %}

package:
  name: xerces-c
  version: {{ version }}

source:
  fn: xerces-c-{{ version }}.tar.gz
  url: http://apache.uberglobalmirror.com//xerces/c/3/sources/xerces-c-{{ version }}.tar.gz
  md5: 21bb097b711a513275379b59757cba4c

build:
  number: 4
  features:
    - vc{{ vc }}  # [win]
  run_exports:
    # changes SO names at minor rev
    - {{ pin_subpackage('xerces-c', max_pin='x.x') }}

requirements:
  build:
    - perl  # [not win]
  host:
    - icu   # [not win]

test:
  commands:
    - conda inspect linkages -p $PREFIX xerces-c  # [not win]
    - conda inspect objects -p $PREFIX xerces-c  # [osx]

about:
  home: http://xerces.apache.org/xerces-c/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Xerces-C++ is a validating XML parser written in a portable subset of C++.'

extra:
  recipe-maintainers:
    - gillins
    - groutr
    - ocefpaf
