travis:
  secure:
    BINSTAR_TOKEN: YpgUSVq7X+65Ueb+NbyPQ26b3KvEY4gA2f/OOB7y6RjAsNb8kU94IDm5RixyKhkqtNraTbl8k1mQrqIdIDrxTg7/b7HwoOUZ2Y6BNd+SG3Okmo7C2atv6CJwzCDJYUNW7m80kIpxeiPoU8ZhLyuXfaKowOuhOeBon9yTU32aoVyBfhJ8cw3SnTzVv6MUK+W52vjqG3JIFcYuGNRdJX08upkkTN343lVOP2seJZ436BWjwEzZADtiun23ls/ZdPUrP9l9qKRumsfTLfeFWJwkgOWqhqovw5QFj4ge85kSEt8gky3Oirq9So3LrFPZKyvX8KlcaT2l+z9IWeRvp1B5PqSmHWGY4aOa5DCqC9Y/h+tr9IK4Fby72WX+D0jPFGk93pfFfz29wqVW/h63rUWPYPwKkev6D+0pgjud++ULnsMIOYj0jJMqveAEwE5QnuDCGVhzizhGOUOv51bkw9V8ojb3H9vaOxT4XogPfwiFQq9mlwbTDgMm2DpCmWb1UAFKZd0KaRDyKNK8AjF7V+dtGC4cU5LbZN5E7Wz0i9/weTssrQh/dKwEiLRmQf135jnC8HrpYo0c65IoslmQXI4359+VGN3iAxrj7zOm5vOWCBJOsDUNIdHoAR3Hjr71I9Ye1ricW3kWRzK7UTGs0vfNqXqRAb1Y138p5jdPO3z51jk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
